Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 12344
  config.vm.synced_folder "docker-files/","/home/docker-images"
  config.ssh.forward_agent = true
   
end